const jwt = require('jsonwebtoken');
const OpenAI = require('openai');
const db = globalThis.__pc || (globalThis.__pc = {users:new Map(), personas:new Map([[1,{id:1,name:'Demo Persona',description:'Create your own persona in Admin',language:'Banglish',personality:'Friendly, casual',chatStyle:'short casual messages',emojiStyle:'medium',avgResponseLength:35,commonPhrases:'["acha","hmm","thik ache"]',vocabulary:'[]',emotionalPatterns:'[]',systemPrompt:'',sourceData:'{}',active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]]), chats:new Map(), seq:{u:1,p:2,c:1,m:1}});
const secret=()=>process.env.SESSION_SECRET||'CHANGE_THIS_SECRET_FOR_PRODUCTION';
const out=(res,s,b)=>{res.status(s).json(b)};
const admin=req=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');return jwt.verify(t,secret()).role==='admin'}catch{return false}};
async function body(req){if(req.method==='GET')return{};return await new Promise((ok,no)=>{let x='';req.on('data',c=>x+=c);req.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch{no(Error('Invalid JSON'))}})})}
function personaPrompt(p){return `You are an AI simulation of the documented communication style for ${p.name}. Never claim to be the real person. Language: ${p.language}. Style: ${p.chatStyle}. Personality: ${p.personality}. Emoji: ${p.emojiStyle}. Common expressions: ${p.commonPhrases}`}
module.exports=async(req,res)=>{try{const u=new URL(req.url,'https://pc.local'),p=u.pathname,b=await body(req);
if(req.method==='POST'&&p==='/api/auth/user'){const id=String(b.userId||'').trim();if(!/^[A-Za-z0-9_-]{3,64}$/.test(id))return out(res,400,{error:'Invalid User ID'});if(!db.users.has(id))db.users.set(id,{id:db.seq.u++,userId:id,createdAt:new Date().toISOString(),lastActiveAt:new Date().toISOString()});return out(res,200,{userId:id})}
if(req.method==='POST'&&p==='/api/auth/admin/login'){const ok=String(b.username||'')===(process.env.ADMIN_USERNAME||'Prodipta')&&String(b.password||'')===(process.env.ADMIN_PASSWORD||'CHANGE_THIS_PASSWORD');if(!ok)return out(res,401,{error:'Invalid admin credentials'});return out(res,200,{token:jwt.sign({role:'admin',username:b.username},secret(),{expiresIn:'8h'}),username:b.username})}
if(req.method==='GET'&&p==='/api/personas')return out(res,200,[...db.personas.values()].filter(x=>x.active));
if(req.method==='GET'&&p==='/api/personas/all'){if(!admin(req))return out(res,401,{error:'Unauthorized'});return out(res,200,[...db.personas.values()])}
if(req.method==='POST'&&p==='/api/personas'){if(!admin(req))return out(res,401,{error:'Unauthorized'});const now=new Date().toISOString(),x={id:db.seq.p++,name:String(b.name||'New Persona').trim(),description:b.description||'',language:b.language||'Banglish',personality:b.personality||'',chatStyle:b.chatStyle||'short casual messages',emojiStyle:b.emojiStyle||'medium',avgResponseLength:0,commonPhrases:'[]',vocabulary:'[]',emotionalPatterns:'[]',systemPrompt:'',sourceData:'{}',active:false,createdAt:now,updatedAt:now};db.personas.set(x.id,x);return out(res,201,x)}
if(req.method==='PUT'&&/^\/api\/personas\/\d+$/.test(p)){if(!admin(req))return out(res,401,{error:'Unauthorized'});const id=Number(p.split('/').pop()),x=db.personas.get(id);if(!x)return out(res,404,{error:'Persona not found'});Object.assign(x,b,{updatedAt:new Date().toISOString()});return out(res,200,x)}
if(req.method==='POST'&&p==='/api/chat/start'){const id=Number(b.personaId),x=db.personas.get(id);if(!x||!x.active)return out(res,404,{error:'Persona not available'});const uid=String(b.userId||'');if(!db.users.has(uid))return out(res,401,{error:'Invalid User ID'});const c={id:db.seq.c++,userId:uid,personaId:id,isAdminConversation:false,createdAt:new Date().toISOString(),lastActiveAt:new Date().toISOString(),messages:[]};db.chats.set(c.id,c);return out(res,200,{conversationId:c.id,persona:x})}
if(req.method==='GET'&&/^\/api\/chat\/\d+$/.test(p)){const c=db.chats.get(Number(p.split('/').pop()));if(!c)return out(res,404,{error:'Conversation not found'});return out(res,200,{...c,persona:db.personas.get(c.personaId)})}
if(req.method==='POST'&&/^\/api\/chat\/\d+\/message$/.test(p)){const id=Number(p.split('/')[3]),c=db.chats.get(id);if(!c)return out(res,404,{error:'Conversation not found'});const text=String(b.message||'').trim();if(!text)return out(res,400,{error:'Empty message'});c.messages.push({id:db.seq.m++,role:'user',content:text,createdAt:new Date().toISOString()});if(!process.env.OPENAI_API_KEY)return out(res,503,{error:'OPENAI_API_KEY is not configured in Vercel Environment Variables'});const ai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const x=await ai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'system',content:personaPrompt(db.personas.get(c.personaId))},...c.messages.slice(-20).map(m=>({role:m.role,content:m.content}))],max_output_tokens:300});const m={id:db.seq.m++,role:'assistant',content:x.output_text?.trim()||'hmm 😅',createdAt:new Date().toISOString()};c.messages.push(m);c.lastActiveAt=new Date().toISOString();return out(res,200,{message:m})}
if(req.method==='GET'&&p==='/api/admin/users'){if(!admin(req))return out(res,401,{error:'Unauthorized'});return out(res,200,[...db.users.values()])}
if(req.method==='GET'&&p==='/api/admin/conversations'){if(!admin(req))return out(res,401,{error:'Unauthorized'});const q=(u.searchParams.get('q')||'').toLowerCase();const rows=[...db.chats.values()].map(c=>({...c,user:db.users.get(c.userId),persona:db.personas.get(c.personaId),_count:{messages:c.messages.length}})).filter(c=>!q||c.user.userId.toLowerCase().includes(q)||c.persona.name.toLowerCase().includes(q));return out(res,200,rows)}
return out(res,404,{error:'Not found'})}catch(e){return out(res,500,{error:e.message||'Server error'})}};
